server:
  port: 7777
  
spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexSanti33/microservices-configs.git
          default-label: main
          clone-on-start: true
          username: AlexSanti33
          password: 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

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}    